services:
  backend:
    build: .
    depends_on:
      database:
        condition: service_healthy
      s3:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/KuzyaDatabase
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
      S3_URL: http://s3:9000
  
  #        volumes:
  #            - .:/app
  
  database:
    image: postgres:16.3-alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: KuzyaDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
  #        volumes:
  #            - ./postgres-data:/var/lib/postgresql/data
  
  s3:
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    
    command: server --console-address ":9001" /data
#        volumes:
#            - ./minio-data:/data